<a href="https://colab.research.google.com/github/jugernaut/TallerMeIA/blob/main/Eval/Ejemplos/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Perceptrón</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M. en C. Miguel Angel Pérez León</i></h5>
</font>

In [ ]:
# bibliotecas que se van a usar
import numpy as np
import matplotlib.pyplot as plt
from macti.evaluation import *
#file_answer = FileAnswer()

In [ ]:
# EJECUTAR ESTA CELDA SOLO SI EL NOTEBOOK ESTA EN MACTI
#from macti.evaluation import Quizz
#quizz = Quizz('1', 'AnalisisNumerico', 'local')

<div class="alert alert-success">

# Objetivos

Construir un perceptrón que sea capas de aprender el comportamiento del operador lógico XOR.

<div class="alert alert-success">
    
## (10 Puntos) Perceptrón XOR

Dado que ya conoces como funcionan los perceptrones vistos en clase, esta tarea consiste es encontrar la forma de aprender el comportamiento del operador lógico XOR mediante el uso de la clase `Perceptron`.

A continuación se muestra la tabla de verdad del operador lógico XOR, así como el código de la clase antes mencionada.

| $x_1$ | $x_2$ | $and$ |
| :-:   |    :-:|  :-:  |
| 0     | 0     | 0     |
| 0     | 1     | 1     |
| 1     | 0     | 1     |
| 1     | 1     | 0     |

In [ ]:
'''
MIT License
Copyright (c) 2018 Thomas Countz
Codigo tomado del sitio
https://medium.com/@thomascountz/19-line-line-by-line-python-perceptron-b6f113b161f3
'''
import numpy as np

# Definicion de la clase que hereda de la clase object
class Perceptron(object):
  '''
  Constructor que recibe los siguientes parametros
  num_entradas:     numero de entradas del vector de entradas
  limite:           es el limite de iteraciones mientras entrenamos
  tasa_aprendizaje: magnitud en la que se incrementan los pesos
  '''
  def __init__(self, num_entradas, limite=15, tasa_aprendizaje=0.01):
    self.limite = limite
    self.tasa_aprendizaje = tasa_aprendizaje
    self.pesos = np.zeros(num_entradas + 1) #se suma uno por el bias

  '''
  Metodo que nos devuelve la prediccion del perceptron
  entradas: vector de entradas para realizar la prediccion
  '''
  def prediccion(self, entradas):
    # suma ponderada x*w, pesos[0] = bias
    suma = np.dot(entradas, self.pesos[1:]) + self.pesos[0]
    # funcion de activacion equivalente a np.heaviside
    if suma > 0:
      activacion = 1
    else:
      activacion = 0
    return activacion

  '''
  Metodo que entrena al percetron
  entradas_ent: vector de vectores de entradas para entrenar
  etiquetas:    valores esperados por cada entrada del vector de entradas
  '''
  def entrenamiento(self, entradas_ent, etiquetas, debbug=False):
    # por cada epoca en el limite de entrenamientos
    for _ in range(self.limite):
      # tomamos una entrada y su respectiva etiqueta
      for entrada, etiqueta in zip(entradas_ent, etiquetas):
        prediccion = self.prediccion(entrada)
        # ajuste de pesos w <- w + (y-f(x)) * x
        self.pesos[1:] += self.tasa_aprendizaje * (etiqueta - prediccion) * entrada
        # ajuste del bias
        self.pesos[0] += self.tasa_aprendizaje * (etiqueta - prediccion) # *1
        # (SECCION DE DEBUGEO)
        if debbug:
          if prediccion != etiqueta:
            print("chanclazo por no aprender")
            input("Continuar?")
          else:
            print("bien hecho muchacho")
            input("Continuar?")
          #self.grafica()

  def grafica(self):
     print(self.pesos)
     # dominio de la grafica
     dominio = np.linspace(-0.25, 1.25, 10)
     # funcion a graficar
     graf = lambda x: (-self.pesos[0]-self.pesos[1]*x)/self.pesos[2]

     # definimos algunos parámetros para la gráfica
     fig, ax = plt.subplots()
     # recta generada por el perceptron
     ax.plot(dominio, graf(dominio))
     # valores de entrada para el perceptron
     xs = [0,1,0,1]
     ys = [0,0,1,1]
     # etiquetas
     ax.scatter(xs, ys)
     ax.annotate('(0,0)', (xs[0],ys[0]), xytext=(0.125, 0.125), arrowprops = dict(  arrowstyle="->",
                            connectionstyle="angle3,angleA=0,angleB=-90"))
     ax.annotate('(1,0)', (xs[1],ys[1]), xytext=(1, 0.125), arrowprops = dict(  arrowstyle="->",
                            connectionstyle="angle3,angleA=0,angleB=-90"))
     ax.annotate('(0,1)', (xs[2],ys[2]), xytext=(0.125, 0.75), arrowprops = dict(  arrowstyle="->",
                            connectionstyle="angle3,angleA=0,angleB=-90"))
     ax.annotate('(1,1)', (xs[3],ys[3]), xytext=(1, 0.75), arrowprops = dict(  arrowstyle="->",
                            connectionstyle="angle3,angleA=0,angleB=-90"))
     # ejes coordenados
     ax.axhline(y=0, color='k')
     ax.axvline(x=0, color='k')
     plt.title("Perceptrón")

     plt.grid()
     plt.show()

<div class="alert alert-success">
    
## Solución al problema

En el siguiente [enlace](https://towardsdatascience.com/how-neural-networks-solve-the-xor-problem-59763136bdd7) puedes encontrar una descripción más detallada del problema y de una posible solución. No es necesario redefinir la clase `Percetron`, solo hace falta usar la clase `Perceptron` que ya fue definida.

In [ ]:
# entrenamiento OR
entradas_ent0 = []
entradas_ent0.append(np.array([1, 1]))
entradas_ent0.append(np.array([1, 0]))
entradas_ent0.append(np.array([0, 1]))
entradas_ent0.append(np.array([0, 0]))

etiquetas0 = np.array([1, 1, 1, 0])
# entrenamiento NAND
entradas_ent1 = []
entradas_ent1.append(np.array([1, 1]))
entradas_ent1.append(np.array([1, 0]))
entradas_ent1.append(np.array([0, 1]))
entradas_ent1.append(np.array([0, 0]))

etiquetas1 = np.array([0, 1, 1, 1])

# entrenamiento AND
entradas_ent2 = []
entradas_ent2.append(np.array([1, 1]))
entradas_ent2.append(np.array([1, 0]))
entradas_ent2.append(np.array([0, 1]))
entradas_ent2.append(np.array([0, 0]))

etiquetas2 = np.array([1, 0, 0, 0])

perceptron_or = Perceptron(2)
perceptron_or.entrenamiento(entradas_ent0, etiquetas0)


perceptron_nand = Perceptron(2)
perceptron_nand.entrenamiento(entradas_ent1, etiquetas1)

perceptron_and = Perceptron(2)
perceptron_and.entrenamiento(entradas_ent2, etiquetas2)

entradas = np.array([0, 0])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

entradas = np.array([1, 0])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

entradas = np.array([0, 1])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

entradas = np.array([1, 1])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

# vector que contiene el sesgo y pesos
print(perceptron_and.pesos)
print(perceptron_or.pesos)
print(perceptron_nand.pesos)

0
1
1
0
[-0.02  0.01  0.02]
[0.   0.01 0.01]
[ 0.03 -0.01 -0.02]


In [ ]:
# EJECUTAR ESTA CELDA SOLO SI EL NOTEBOOK ESTA EN MACTI
#quizz.eval_numeric('1', documento.vector_caracteristico)
entradas = np.array([0, 0])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

file_answer.write('1', documento.vector_caracteristico, 'Revisa la solución del problema')

In [ ]:
entradas = np.array([1, 0])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

file_answer.write('2', documento.vector_caracteristico, 'Revisa la solución del problema')

In [ ]:
entradas = np.array([0, 1])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

file_answer.write('3', documento.vector_caracteristico, 'Revisa la solución del problema')

In [ ]:
entradas = np.array([1, 1])
print(perceptron_and.prediccion(np.array([perceptron_nand.prediccion(entradas), perceptron_or.prediccion(entradas)])))

file_answer.write('4', documento.vector_caracteristico, 'Revisa la solución del problema')